import numpy as np
from scipy.stats import linregress

# Load the data generated by the Master Script
data = np.load('preload_data/preload_etaV2paper1C_robustness_sweep_STATISTICAL.npz')
eta_values = data['eta_values']
mean_nl = data['mean_acc_res_nonlinear']
mean_lin = data['mean_acc_res_linear']

#  Define Regime 
# Indices 7 to 15 correspond to 1.05 <= eta <= 2.00
# This is the "Intermediate" jitter regime used in the Abstract
start, end = 7, 15 

X_sub = eta_values[start:end]
Y_nl_sub = mean_nl[start:end]
Y_lin_sub = mean_lin[start:end]

#  Calculate Slopes 
slope_nl, _, _, _, _ = linregress(X_sub, Y_nl_sub)
slope_lin, _, _, _, _ = linregress(X_sub, Y_lin_sub)

print(f"--- Analysis for Paper Text (Range: {X_sub[0]:.2f} - {X_sub[-1]:.2f}) ---")
print(f"NLSE Decay Rate: {slope_nl:.4f}")
print(f"LSE Decay Rate:  {slope_lin:.4f}")
print(f"Comparison: LSE is {((slope_lin/slope_nl)-1)*100:.1f}% steeper than NLSE")